# tmpfiles.d(5) config for tuned
#
# Type  Path            Mode    User            Group           Age     Argument
d       /var/lib/tuned  0755    root            root     -       -
d       /var/log/tuned  0755    root            root     -       -
D       /var/run/tuned  0755    root            root     -       -
